euclidean_cluster_node:
  ros__parameters:
    use_height: false
    min_cluster_size: 70
    max_cluster_size: 5000
    distance_threshhold_seg: 0.02
    tolerance: 0.02
    max_height: 100.0
    min_height: 0.05
    max_width: 100.0
    min_width: 0.01
    max_depth: 100.0
    min_depth: 0.01
    max_zx: 1000.0
    min_zx: 1.0
    max_zy: 1000.0
    min_zy: 1.0
